import { HorizontalBox, VerticalBox, GridBox, Palette } from "std-widgets.slint";

export struct SlintAlembicMetadataItem {
    key: string,
    value: string,
}

export struct SlintAlembicNodeListItem {
    indentation: int,
    name: string,
    metadata: [SlintAlembicMetadataItem],
}

export component AlembicNodeList inherits VerticalLayout {
    in-out property <length> indent_width;
    in-out property <[SlintAlembicNodeListItem]> nodes;

    for node in nodes : HorizontalLayout {
        padding-bottom: 1rem;

        indent_block := Rectangle {
            width: indent_width * node.indentation;
        }

        content_block := Rectangle {
            content := VerticalLayout {
                Text {
                    text: node.name;
                    font-weight: 700;
                }
                VerticalLayout {
                    for metadata_item in node.metadata: HorizontalLayout {
                        Text {
                            text: "\{metadata-item.key}: ";
                            color: Palette.foreground.darker(0.5);
                        }
                        Text {
                            text: metadata-item.value;
                            horizontal-alignment: left;
                            horizontal-stretch: 1;
                        }
                    }
                }
            }
        }
    }
}