import { Button, ComboBox, VerticalBox, HorizontalBox, Palette, ScrollView, GridBox, LineEdit, TextEdit } from "std-widgets.slint";

import { AbcListView, AbcKvEntry, AbcNode } from "abc_list_view.slint";
import { AboutPopupContent, AppInfo } from "about_popup.slint";

export component AppWindow inherits Window {
    title: app_info.name;
    icon: @image-url("../asset/icon-64.png");
    preferred-width: 600px;
    preferred-height: 800px;

    in property <AppInfo> app_info;

    in property <string> file_path: "";
    property <bool> is_file_specified: file_path != "";

    in property <string> error_message;
    property <bool> has_error: error_message != "";

    in property <[AbcKvEntry]> abc_list_view_archive_items;
    in property <[AbcNode]> abc_list_view_nodes; 

    callback open_button_clicked <=> open_button.clicked;
    callback reload_button_clicked <=> reload_button.clicked;
    callback copy_json_button_clicked <=> copy_json_button.clicked;
    callback reload_file;

    about_popup := PopupWindow {
        width: root.width - 2rem;
        padding-right: 1rem;
        x: 1rem;
        y: 1rem;
        AboutPopupContent { app_info: app_info; }
    }
    
    VerticalLayout {
        command_bar := VerticalBox {
            padding-left: 0;
            padding-right: 0;

            HorizontalBox {
                padding-top: 0;
                padding-bottom: 0;

                open_button := Button {
                    text: "📂 Open...";
                    horizontal-stretch: 1;
                }
                reload_button := Button {
                    text: "🔄️ Reload";
                    enabled: is_file_specified;
                }
                copy_json_button := Button {
                    text: "📋 Copy JSON";
                    enabled: is_file_specified;
                }
                about_button := Button {
                    text: "❔";
                    clicked => { about_popup.show() }
                }
            }

            if is_file_specified: GridBox {
                padding-top: 0;
                padding-bottom: 0;

                Row {
                    Text {
                        text: "File";
                        vertical-alignment: center;
                    }
                    LineEdit {
                        text: file_path;
                        read-only: true;
                        colspan: 2;
                    }
                }
            }
        }

        VerticalLayout {
            padding-top: 0;
            padding-bottom: 2px;
            padding-left: 2px;
            padding-right: 2px;

            preferred-width: scroll_inner.preferred-width;
            preferred-height: scroll_inner.preferred-height;

            Rectangle {
                border-width: 1px;
                border-radius: 4px;
                border-color: Palette.border;
    
                ScrollView {
                    scroll_inner := VerticalBox {
                        // Alert box
                        if has_error: Rectangle {
                            padding: 1rem;
                            background: red.with-alpha(0.2);
                
                            Text { 
                                text: error_message;
                                wrap: word-wrap;
                                vertical-alignment: top;
                            }
                        }
                        
                        if !has_error && is_file_specified : AbcListView {
                            indent_width: 16px;
                            archive_items: abc_list_view_archive_items;
                            nodes: abc_list_view_nodes;
                        }
                    }
                }
            }
        }
    }
}
