// DO NOT MODIFY - Auto generated by the CMake configure_file()

#ifndef SESERAGI_APP_H
#define SESERAGI_APP_H

#include <string_view>

namespace seseragi {

constexpr std::string_view AppName = "seseragi";
constexpr std::string_view AppDescription = "A simple GUI tool for checking the hierarchy information of Alembic files";
constexpr std::string_view AppVersion = "0.1.0";
constexpr std::string_view AppUrl = "https://github.com/ugai/seseragi";

} // namespace seseragi
#endif // SESERAGI_APP_H
