// DO NOT MODIFY - This file is auto-generated by the CMake configure_file() command.

#ifndef SESERAGI_APP_H
#define SESERAGI_APP_H

#include <string_view>

namespace seseragi {

constexpr std::string_view AppName = "seseragi";
constexpr std::string_view AppDescription = "Alembic hierarchy viewer GUI.";
constexpr std::string_view AppVersion = "0.1.0";
constexpr std::string_view AppUrl = "https://github.com/ugai/seseragi";

} // namespace seseragi
#endif // SESERAGI_APP_H
